services:
  minio:
    image: quay.io/minio/minio:latest
    container_name: minio
    restart: always
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin123
      MINIO_DEFAULT_BUCKETS: dev-video-bucket
    command: server /data --console-address ":9001"
    volumes:
      - ./minio_data:/data
      - ./cors.json:/root/.minio/config/cors.json

  postgres:
    image: postgres:16
    container_name: postgres_dev_nextviso
    restart: always
    environment:
      POSTGRES_USER: viso_user
      POSTGRES_PASSWORD: viso_password_123
      POSTGRES_DB: viso_db
    ports:
      - "5599:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  # app:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   container_name: blitz_app
  #   restart: always
  #   depends_on:
  #     - postgres
  #     - minio
  #   environment:
  #     DATABASE_URL: postgres://blitz_user:blitz_password@postgres:5432/blitz_db
  #     MINIO_ENDPOINT: http://minio:9000
  #     MINIO_ACCESS_KEY: minioadmin
  #     MINIO_SECRET_KEY: minioadmin123
  #     PORT: 3000
  #   ports:
  #     - "3000:3000"
